### ISSUE TITLE
Regression: Duplicate entry in short language selection menu

### ISSUE THREAD

**Issue by frafum** [ipomoena/dasher#104]
Hi, 

I am using dasher with 5 different languages. 

Fortunately, in dasher version 4, the popup menu for the languages at the bottom right of the dasher windows remembers the 5 last used languages. Thus, I don't have to reselect the language from the Preferences window. 

Unfortunately, after the upgrade to dasher beta, there is a regression concerning the 5 last used languages in the short popup menu: in fact, the 5 entries are now in fact 4 different languages and a duplicate of the last selected language. Or in other words, the last selected entry has always a duplicate in the short language menu, reducing the available languages to 4, which is not sufficient for my use case. 

Could you please have a look at the issue and fix the short popup menu with the languages to not have duplicate entries? 

By the way, what do you think about adding an option to the Preferences of dasher to allow the user to choose how many languages are kept in the short popup menu with the languages. 

Finally, thanks for continuing to maintain and enhance dasher; I apprecate for example especially the new feature that automatically copies the written text to the clipboard when the user stops writing. 

Have a nice day.

(Written with dasher 5 beta on Ubuntu linux.)

**Comment by ipomoena** [comment]
I am able to reproduce this bug. Very sorry for introducing it. I will try my best to fix it and release 5.0 final.
Out of curiosity, 5 languages is impressive. Which languages are you using?

**Comment by frafum** [comment]
Thanks for much for taking the bug into account and trying to fix it. 

The languages I am using are: english, french, german, italian and luxembourgish. 

By the way, thanks also for the new feature to have the written text automatically copied to the clipboard when the user stops writing. This saves me from having to manually select the text from the pane at the top of the window and copy it to the clipboard by using the copy button. 8-)

**Comment by frafum** [comment]
Thanks for the fix: I am running revision 6aae7ca on Ubuntu zesty linux and the issue does not occur anymore. 8-) That was fast. :-)
