### ISSUE TITLE
Win32 Dasher direct entry does not work properly

### ISSUE THREAD

**Issue by Dimdoum** [ipomoena/dasher#115]
Hello 
first of all, sorry for my english, i'm from France.
I'm a new user of Dasher and i would like to use it for pretty much everything because i'm disabled.
The problem is, when i put the software in "direct entry" mode (the most useful in my opinion), it has a strange issue. When i start wrighting a word, in the middle of it, it goes back to the beginning, as if i was starting a new sentence... 
It is really annoying... Could you please help me ?
I use windows 10, 64 bits

**Comment by frafum** [comment]
If you can also use an on-screen keyboard, you might perhaps use dasher and the on-screen keyboard to get better control of the desktop. 

Dasher 5 comes with the new option to automatically put the written text into the clipboard on every write stop. This facilitates the following work flow in dasher: 
- You write the text with dasher in non-direct mode. 
- You do a paste into the document you are writing (you don't have to copy the text to the clipboard; there is a setting to have dasher do it automatically on write stop (at least in dasher 5 on linux.))
- Click on the new document icon on the toolbar of Onboard to clear the text pane in dasher.

Keep the on-screen keyboard to perform modifier+mouseclicks (for example control + click for multiple selection) or to enter shortcuts (for example control+a to do a "select all") 

I am aware that my comment goes beyond the scope of this bug thread; but I thought that they might be useful to the original poster of this thread. 

Hoping to have been helpful. 

(Written with dasher pre5 in non-direct mode by using the work flow described above. I performed 3 pastes, as I am used to do a paste after a few sentences and then I go on with writing after clearing the panel.)

**Comment by Dimdoum** [comment]
Thank you for your answer.
If anyone has a solution for my problem, it would be nice though...

**Comment by Dimdoum** [comment]
anyone else ?

**Comment by cagdasgerede** [comment]
How can we reproduce it? Does it always happen? Could you give more details?

**Comment by ipomoena** [comment]
I see the same problem on my new tablet. It was not happening on old tablet. Also with Dasher 5.0.
There is mechanism to reset to new sentence, every time the window with focus changes. Which is good, unless some badly written background application is stealing focus for a fraction of the second.
For me, it is not big problem, because it is happening only occasionally.
Since it is problem for other people also, I will try to fix it. It should not be hard. 
_

**Comment by Dimdoum** [comment]
Thank you Ipomoena. I'm waiting for your repair. Could you let me know when you will have some news about it ?
