### ISSUE TITLE
Dasher 5.0 with Win 10 only will speak in female voice

### ISSUE THREAD

**Issue by mattherd** [ipomoena/dasher#116]
All of the sudden Dasher is using a female voice to speak. Ive checked the TTS voices in Windows and they are set to a male voice. Does anyone have any suggestions on how to resolve ? The user is pretty frustrated and uses dasher for communication. Ive tried uninstall, reset computer to defaults and verified TTS voices. User has a Win 10 Surface 4 any help would be appreciated.

**Comment by cagdasgerede** [comment]
@ipomoena

**Comment by ipomoena** [comment]
I found a way to change default system voice. It is not obvious. It is documented now in Dasher 5.0 felease notes. Please follow instructions here:
https://docs.google.com/document/d/1TwDCWIh5KDulHtPyvSTjr-dPzJ5C8mgxmNhsXUwONR0
And let me know if it can be explained better.
Happy to see other people using Dasher for speaking.

**Comment by ipomoena** [comment]
This is better URL. https://tinyurl.com/l3woq4h

**Comment by mattherd** [comment]
Thank you.

On Apr 22, 2017, at 6:41 AM, Ada Majorek <notifications@github.com<mailto:notifications@github.com>> wrote:


This is better URL. https://tinyurl.com/l3woq4h

-
