### ISSUE TITLE
Speak-New fried after Delete

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#12]
The Speak-New command in the Control box sometimes (often) doesn't work or it says a bunch of numbers and nonsense. It works fine when you first start but the first time I use the delete in the control box, the Speak-New gets fried every time.

**Comment by ipomoena** [comment]
@smoothsaling please reopen if next dasher.exe doesn't fix it.

**Comment by ipomoena** [comment]
https://drive.google.com/open?id=0B1rM5ktyjw-tNVpoZVMyc3VDZ2s
try this exe

**Comment by smoothsaling** [comment]
Hey, it seems to work perfectly. TY

FYI, I emailed Lynne Nieto yesterday and asked about Augie using TypeRight
and Troy. We'll see.

Steve
------------------------------


*Steve Saling - ALSRI.org <http://ALSRI.org>WALK for LIVING -
http://give.chelseajewish.org/goto/smoothsaling2015
<http://give.chelseajewish.org/goto/smoothsaling2015>*
