### ISSUE TITLE
Change color of pause control

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#16]
Another minor issue but I wish the pause control could be a color other than yellow because it looks the same as the capital letters. I would avoid red because that is the color of numbers. Maybe orange or a dark blue. I use the default European/Asian color scheme.

**Comment by ipomoena** [comment]
You will be able to use any color once whole control box moves to control.xml
Depends on https://github.com/ipomoena/dasher/issues/11

**Comment by ipomoena** [comment]
all comands are in  control.xml and colors can be changed
