### ISSUE TITLE
autogen.sh fails with "configure: error: No method to send characters into another application found"

### ISSUE THREAD

**Issue by dbarnett** [ipomoena/dasher#23]
I'm trying to build dasher from source on Ubuntu Linux 14.04, but running `./autogen.sh` I get a failure with this output:
```
…
checking for XML_Parse in -lexpat... yes
checking for ATSPI... no
checking for CSPI... no
checking for XTestFakeKeyEvent in -lXtst... no
configure: error: No method to send characters into another application found
```

Any idea what dependencies I need to install to satisfy that check?

**Comment by dbarnett** [comment]
I ran `sudo apt-get build-dep dasher` and that resolved the missing dependencies for me. Looks like `libatspi2.0-dev` was the specific package I was missing.

**Comment by ipomoena** [comment]
Can you add sudo apt-get build-dep dasher step to build instructions if it is not there yet?

**Comment by dbarnett** [comment]
INSTALL.Linux does mention to install libatspi2.0-dev, I just missed it. Listing the individual deps for the latest Dasher like it does is better than `sudo apt-get build-dep dasher` since that command gives you build deps for the version in Ubuntu, which may be out of date for building the latest development version.
