### ISSUE TITLE
Speech should use language for selected alphabet

### ISSUE THREAD

**Issue by dbarnett** [ipomoena/dasher#31]
Dasher should speak in the language corresponding to the selected alphabet instead of speaking everything as if it were in the system locale's language. For instance, if you select the French alphabet and enter some French words, it should speak those words using French pronunciation regardless of whether the system locale is set to `en`, `es`, or any other language's locale.

**Comment by dbarnett** [comment]
@sehtia and I will work on this.

**Comment by dbarnett** [comment]
@sehtia submitted #34, #35, #36, #37, and #38 for this.
Looks like language codes for Turkish, Polish, and Swedish (https://github.com/ipomoena/dasher/compare/master...ipomoena:sehtia-patch-5) still haven't been submitted?

**Comment by sehtia** [comment]
Hey David,
They should be submitted now. Thanks

**Comment by ipomoena** [comment]
Cool. Who is FlufyKoan?

:-) Ada
