### ISSUE TITLE
Control box delete problem in 10/10 version

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#32]
In the Oct10 version, there is a problem with the control box delete options. All 4 of the delete back options only move the cursor to the beginning of the text but don't delete anything. The delete forward works but only after first returning to the beginning of the text so it deletes the wrong text.

**Comment by ipomoena** [comment]
Please sync to latest code and copy latest control.xml.

I didn't test my previous change well enough. And needed to correct it
later.
https://github.com/ipomoena/dasher/commit/1c475c523f63601db1ccdc4093249e243745b754
Sorry for that.

:-) Ada

**Comment by ipomoena** [comment]
oops. I didn't look who wrote this bug. I though developer. I will build
new executable and let you know.

:-) Ada

**Comment by ipomoena** [comment]
Fixed version available here https://drive.google.com/drive/folders/0B1rM5ktyjw-tfkF4cGVIZ3B0NUhSUVU5NUFSVnRyLVR6ek5Pc1RTVk5tWWVaQ0RSLWMtMUU
Please also copy new control.xml to system.rc. All control box commands are read from this file. You can change pause color now, or remove pause completely.
control.dtd has formal description of commands and parameters. 
speak what='paragraph' and speak what='sentence' do not work yet.

**Comment by smoothsaling** [comment]
What is the color chart used please.

**Comment by ipomoena** [comment]
Please, hold on. Oct16 version has broken speech.

:-) Ada

**Comment by ipomoena** [comment]
Oct17 version should work 
speak what='paragraph' and speak what='sentence' work also. 
default colors for English are defined here
https://github.com/ipomoena/dasher/blob/master/Data/alphabets/alphabet.english.xml#L8
<palette>European/Asian</palette>

This palette is defined in
https://github.com/ipomoena/dasher/blob/master/Data/colours/colour.euroasian3.xml#L5
at the end of this file there are control box colors. 
https://github.com/ipomoena/dasher/blob/master/Data/colours/colour.euroasian3.xml#L408
I think you can add more 243, 244,...

**Comment by smoothsaling** [comment]
It works awesomely. I am curious how you use the speak sentence and speak
paragraph options? Or are you just showing what is possible?

It is not a problem for me because I will delete it anyway but the stop
control box option doesn't work at all. The pause does the same function so
I delete stop anyway.

I will send this version to 3 users for trial and comment. Thank you.

Steve
------------------------------


*Steve Saling - ALSRI.org <http://ALSRI.org>WALK for LIVING -
http://give.chelseajewish.org/goto/smoothsaling2015
<http://give.chelseajewish.org/goto/smoothsaling2015>*

**Comment by ipomoena** [comment]
Family dinner. I am writing about something funny what happen at work. I am in the middle of writing it. It already took me 3 minutes to write it.
Then my aunt asks me about spices I want on the main course. 
It is to complicated for simple yes/no answers. No problem. I  create new paragraph in dasher, write spices names and navigate through speak paragraph command in control box. Once aunt knows the answer, I can go back to finishing and saying work story.

Another use-case is list of prepared questions for the doctor. You want to ask them, but order is uncertain and probably doctor will ask you many other questions before you have a chance to ask yours.

Speaking longer text. It is nice to control how much silence is between sections. I will make paragraphs from distinct sections and speak one paragraph at a time. It may be nice to combine speaking paragraph with moving to next paragraph
    ` <speak what="paragraph"/>
      <move forward="yes" dist="paragraph"/>`
