### ISSUE TITLE
Speak-New doesn't work when the cursor is relocated 

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#33]
In the Oct10 version (and maybe before), there is still a problem with the speak new. It seems to work fine as long as the cursor does not change position but if the cursor is relocated to insert words within previously typed text, it messes up what it speaks so that instead of speaking the newly typed text, it speaks some of the previously typed text that happens to be at the end of the text string.

**Comment by ipomoena** [comment]
What it does right now is remembers how long was whole text when spoken. And then speak new speaks only the fragment which is longer than previous text.

Was it working better before?
What would you expect to happen in following scenario?
Nice to meet you<speak all>
<move back all>
<delete forward char>
Very n<speak new>

**Comment by ipomoena** [comment]
Speak new will never work perfectly with editing commands.
There are now other ways to achieve the same goal (speak paragraph, sentence). Closing the issue.
