### ISSUE TITLE
Dasher should fail for unrecognized command-line args

### ISSUE THREAD

**Issue by dbarnett** [ipomoena/dasher#40]
Unrecognized command-line args usually cause programs to fail with an exit code, e.g.

```
$ ls --walrus-face
ls: unrecognized option '--walrus-face'
Try 'ls --help' for more information.
```

But dasher will happily start the GUI no matter what options I pass it:

```
$ dasher --walrus-face
** Message: Opening GUI file: /usr/local/share/dasher/dasher.traditional.ui
```

Could we make it validate that it doesn't receive any unrecognized args?

**Comment by cagdasgerede** [comment]
Mursel will work on this.

**Comment by miroslavca** [comment]
Hi @cagdasgerede 
It looks like the feature mentioned in the issue description has been added already.
I got the following output:

`$ dasher --walrus-face`
`option parsing failed: Unknown option --walrus-face`

Dasher fails to start GUI as expected.

**Comment by cagdasgerede** [comment]
In that case, can we make it so that it says

"Try 'dasher --help' for more information."

after it says

"option parsing failed: Unknown option --walrus-face"?
