### ISSUE TITLE
Dasher speech stops working on program close/restart

### ISSUE THREAD

**Issue by dbarnett** [ipomoena/dasher#44]
If I open Dasher, go to Preferences, and uncheck/recheck "Speak words as you write", then Dasher speaks each word as I pass through it. But if I close and reopen dasher, speech stops working until I repeat the uncheck/recheck step in Preferences.

I see this on Ubuntu Linux 14.04.

**Comment by ipomoena** [comment]
Oh, same thing is happening on windows.
