### ISSUE TITLE
Multiple alphabets in same alphabet file should share langcode

### ISSUE THREAD

**Issue by dbarnett** [ipomoena/dasher#53]
In the alphabet files in Data/alphabets/, it feels brittle duplicating the same langcode into multiple alphabets for the same language when it's generally the same for every alphabet in the same alphabet file. Any alphabet that doesn't have the same langcode as the others in the file is very likely to be a bug.

What would you think about making it an attribute or subelement at the "`<alphabets>`" level?

**Comment by ipomoena** [comment]
Alphabets attribute sounds great.

:-) Ada

**Comment by dbarnett** [comment]
Ada, can you point me to where the code should handle the XML "alphabets" tag? I found a bunch of related code in Src/DasherCore/Alphabet/AlphIO.cpp, but I couldn't tell for sure if I could just add "alphabets" in with the other tags handled there and how the nesting of the structure is represented in that parsing.

**Comment by ipomoena** [comment]
I think you should add alphabets handling and extract language value from
lang attribute in start handler.
. And clear that value in end handler.
Then, for every alphabet assign whatever is in tat variable.

:-) Ada
