### ISSUE TITLE
Linux:Option to disable confirm on quit

### ISSUE THREAD

**Issue by dbarnett** [ipomoena/dasher#54]
I'd like an option in Dasher Preferences to disable the "Are you sure you wish to quit?" prompts when I try to close Dasher.

When there's unsaved text there's a slightly different "Do you want to save your changes?" with a few additional options for saving to a file. I'd like to be able to turn that off, too, and only save explicitly, possibly as an additional option to not prompt for unsaved changes.

**Comment by ipomoena** [comment]
David, Have a look at this commit implementing "Confirm unsaved changes" configuration option for windows. It is used not only on quite. Also when loading file or on new file.
https://github.com/ipomoena/dasher/commit/bee3f2a93ac5e90bf53b3e0b675ae1d3a50c59a5

It should be pretty easy to add checkbox to preferrences dialog and use that property to decide whether to display warning dialog or not.

**Comment by cagdasgerede** [comment]
Ayşe will work on this.

**Comment by cagdasgerede** [comment]
For a new checkbox in the preferences window, take a look at "dasher.preferences.ui" and add something like this:

```
                    <child>
                      <object class="GtkCheckButton" id="hello_world">
                        <property name="visible">True</property>
                        <property name="can_focus">True</property>
                        <property name="border_width">2</property>
                        <property name="label" translatable="yes">Hello World</property>
                        <property name="use_underline">True</property>
                        <property name="draw_indicator">True</property>
                        <signal handler="generic_bool_changed" name="clicked"/>
                      </object>
                      <packing>
                        <property name="expand">False</property>
                        <property name="fill">False</property>
                        <property name="position">8</property>
                      </packing>
                    </child>
```
