### ISSUE TITLE
Linux: Status bar speed and alphabet display should update when parameters change

### ISSUE THREAD

**Issue by ipomoena** [ipomoena/dasher#61]
See Win32 implementation. Should be relatively easy to copy. https://github.com/ipomoena/dasher/commit/9edabd95b79dddf397837cdca16dee651f63a145

**Comment by cagdasgerede** [comment]
Mürsel will work on this.

**Comment by cagdasgerede** [comment]
@ipomoena How can I reproduce this? I am not sure what parameters to change to observe the problem and also not sure where to look for "Status bar speed and alphabet display".

Is this referring to the status bar speed and alphabet display shown at the very bottom of the following Figure:
![image](https://cloud.githubusercontent.com/assets/12052/23894663/0efc0ebe-08b4-11e7-9e2a-2902e623ed7f.png)

Also for the parameter change, do we mean modifying "dasher preferences" shown in the following Figure?:

![image](https://cloud.githubusercontent.com/assets/12052/23894685/1e77c144-08b4-11e7-8b16-f9a6ef722c0e.png)


I modified some preferences but the speed and alphabet display seem to continue working after that as expected.

**Comment by ipomoena** [comment]
The easiest way to test it is to check "Adapt speed automatically" checkbox on the control tab in preferrences. When auto is on, speed value changes several times per minute.

**Comment by cagdasgerede** [comment]
I am confused. When I set that, the speed does update if my navigation speed changes. So i cannot observe a bug (i assume you mean that it should change but you observe that it doesn't. However, i am not observing such a problem). Could you please clarify further?

**Comment by ipomoena** [comment]
Apparently, it was working in Linux version all the time.
I noticed and fixed the bug in Win32 version and assumed, that the same problem is on Linux.

Thank you for checking and verifying. I was wrong.
