### ISSUE TITLE
Add language code to all alphabets with spoken language  

### ISSUE THREAD

**Issue by ipomoena** [ipomoena/dasher#63]
Most alphabets are already updated in https://github.com/ipomoena/dasher/commit/6b5101f4f1e3db1b7845202b70dee8f01cdb690d, but more exotic are missing language code.
 Look for alphabets updated earlier than October 2015.

**Comment by dbarnett** [comment]
Got delayed working on this since I was hoping to whip up a script to automatically update language codes and/or eliminate the redundancy in similar alphabets (#53) first. Ping me if I don't get to it within a week or so. =)

**Comment by ipomoena** [comment]
Yay! Thank you.

:-) Ada
