### ISSUE TITLE
Linux -- Add shortcuts for starting dasher in 4 basic profiles

### ISSUE THREAD

**Issue by ipomoena** [ipomoena/dasher#75]
"Dasher for conversation" - dasher --config speak
"Dasher for giving speeches" - dasher --config prepared_speech. 
"Dasher for editing" - dasher --config edit
'"Dasher direct entry" - dasher --config direct

**Comment by cagdasgerede** [comment]
What do we mean here by shortcut?

**Comment by ipomoena** [comment]
I meant icons on the destktop starting dasher with this parameter. Or maybe create shell scripts appropriately named. Or both.
I would like it to be easy to start dasher in different configurations.

**Comment by cagdasgerede** [comment]
I am picking this up now. Feel free to assign it to me. I could not find on the github UI how to do it.

**Comment by ipomoena** [comment]
Thank you. I needed to add you as a collaborator to the project.
