### ISSUE TITLE
Stop command doesn't work

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#90]
In Dasher 5.0, the Stop command in the gray control box doesn't work.

**Comment by ipomoena** [comment]
Jordan,  can you figure out why this is not working. For reference, Pause command works as expected.
Thank you.

**Comment by JordanD113** [comment]
Hey Ada,

Can you explain this to me a little bit? I see that you indicated it has
duplicated logic.

**Comment by ipomoena** [comment]
Previous code was only calling function doing copy all to clipboard and speak all, if necessary. 
https://github.com/ipomoena/dasher/blob/master/Src/DasherCore/DasherInterfaceBase.cpp#L437

The code executed when dasher is stopped (by left click, space or circle starter) is here: 
https://github.com/ipomoena/dasher/blob/master/Src/DasherCore/DefaultFilter.cpp#L179

It was not obvious to me if I can somehow get to default filter instance from pNode and I didn't have much time to investigate. So I copied the logic from stop. As I look at it now, I did sloppy job, even with copying. Order of pause and stop is flipped.

If you can, please figure out how could Stop::happen(...) call stop() on default filter instance.  https://github.com/ipomoena/dasher/blob/master/Src/DasherCore/ControlManager.cpp#L280
