### ISSUE TITLE
Error message on start or changing control mode

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#91]
I am using a 64 bit Windows 7 pro and when I first open Dasher5.0 or change the control mode, there is an error displayed on the Dasher screen. Using the circle to start, the start trips up and stops immediately. After changing control mode, the start trips 8 times in a row before working normally on the 9th start. It is not a big problem with a little patience but annoying. 
[
![d4](https://cloud.githubusercontent.com/assets/14254466/13516175/bb9fa5a6-e185-11e5-9d23-ad1aca811700.jpg)
](url)

**Comment by ipomoena** [comment]
You must have some trash in the training text. I will make temporary fix, to display warnings, but not stop dasher. Then, I will work on handling incorrect bytes better.

**Comment by ipomoena** [comment]
Immediate issue is fixed. I  will open another bug for more graceful handling of trash in training file.
