### ISSUE TITLE
Control text box height as lines of text

### ISSUE THREAD

**Issue by smoothsaling** [ipomoena/dasher#94]
Is it possible to control the height of the text editor box (mine is on top) as a certain number of lines of text based on the size of the font? It is difficult for me to drag the text box with a head mouse and I can't imagine myself doing it with eyegaze. For example, when I am talking in a public place where I expect that someone will be reading my screen, I set the font to 36pt and I like to show 3 lines of text. If I am writing a private letter, I prefer 16pt and 5 lines of text. In an ideal world, there would be 2 programmable buttons on the toolbar so I could toggle between the two. Maybe you could add language and the voice used too. 

Short of the ideal of having programmable buttons in the toolbar, it would be a big help to me if in the preferences dialog box, beside the option to edit the Editor Font, there was an option to control the text box height by the number of lines of the selected font size with a dropdown list of the options. 

Another option that would solve the essential problem and is probably the easiest solution is to be able to set the height of the text box directly in the preferences so that I don't have to drag it.

**Comment by ipomoena** [comment]
What do you think of having separate shortcuts for these two profiles?
You could adapt one of the pre-installed profiles, 
change Dasher for Conversations to have large fonts and larger edit box. And your favorite speed, circle starter and whatever else you want.You would only need to do it once.

 When you want to write private document, you could use Dasher for Editing shortcut. Set smaller fonts, switch to Standard style (or leave composition style you may like it in the private document editing context).
Once you find all your working profiles and configure them, you will never, ever need to change settings.
Instead, you will be switching between different instances of Dasher. 

I have all shortcuts to my working profiles pinned to task bar. This makes switching between them very easy.

**Comment by ipomoena** [comment]
Steve, have you tried different configs for different usage profiles? Did it solve the problem of resizing? Can I close this issue?

**Comment by smoothsaling** [comment]
I edit the settings file to fix it. I hadn't used the different profiles
before because I like having a single control box but it might work well
for public and private writing. I'll give it a try. You can definitely
close the issue. Thanks.

Steve
------------------------------

*Steve Saling - ALSRI.org <http://ALSRI.org>*

**Comment by ipomoena** [comment]
Closing, as there are other ways to achieve the same.
